services:
  mysql:
    image: mysql:8.0.33
    ports:
      - 13306:3306
    volumes:
      - ./src/main/resources/initdb/create_schema.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--lower_case_table_names=1'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: stock