spring:
  application:
    name: "neordinary"

jwt:
  secret:
    access: VTZWa1F6ZzBOMk15TldJM1ptRTVZbVEzTWpKaU4yVTFZamMwTTJVMU1UUTJPR1ppTmpReU5EVTJNelEyTnc
    refresh: WVRrNU5ETmpZVGN5WWpFd05EYzJNMkppWWpZeU1UUmxZekUwTkRFNU1XSTJaV1l3TnpFeU5qYzFNRFEx

oauth:
  naver:
    client-id: LXAke4cz8pwKThYvbGQK
    client-secret: PruqII0pi7
    state: naver
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
      redirect: http://localhost:8080/api/v1/auth/naver/callback

---
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/stock?serverTimezone=UTC&characterEncoding=UTF-8
    username: neordinary
    password: backend
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true